### ISSUE TITLE
[firestore-auth-claims] Specifying "Claims Field" field in the configuration results in error

### ISSUE THREAD

**Issue by taeold** [FirebaseExtended/experimental-extensions#21]
## Expected Behavior
With "claims field" specified in the extension configuration, only the data in that field is synced with the custom claim for the user.

## Actual Behavior
Nothing happens - error message from CF3:

```
Error: CustomUserClaims argument must be an object or null.
  at FirebaseAuthError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:42:28)
  at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:88:28)
  at new FirebaseAuthError (/workspace/node_modules/firebase-admin/lib/utils/error.js:147:16)
  at AuthRequestHandler.AbstractAuthRequestHandler.setCustomUserClaims (/workspace/node_modules/firebase-admin/lib/auth/auth-api-request.js:999:35)
  at Auth.BaseAuth.setCustomUserClaims (/workspace/node_modules/firebase-admin/lib/auth/auth.js:342:40)
  at /workspace/lib/index.js:38:16 at processTicksAndRejections (internal/process/task_queues.js:97:5)
``` 

## Steps to Reproduce the Problem
1. While installing/updating the firestore-auth-claims extension, specify a claims field, e.g. "role".
1. Trigger an extension by manually modifying the content of the document in the collection configured in the extension, e.g. in the `user_claims` collection, set `{ "role": "admin" }`.
1. Auth claims of the user is updated w/ the value of the "role" field in the document.

## Specifications

- Extension name: firestore-auth-claims
- Version: 0.1.0

**Comment by mbleigh** [comment]
@taeold I think this might be WAI, though I can do a friendlier error message. Custom claims have to be an object, and setting a claims field is saying which field that object should be in. What happens if you specify instead: `{"role": {"role": "admin"}}`?
